modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/doonguy/Bad-Horse-Fix/issues"
license = "LGPL-3.0-only"

[[mods]]
modId = "badhorsefix"
version = "${version}"
displayName = "Bad Horse Fix"
authors = "DoonGuy"
description = '''
Fixes horse markings appearing above horse armor when using Oculus
'''
logoFile = "badhorsefix-icon.png"

[[dependencies.badhorsefix]]
modId = "forge"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "CLIENT"

[[dependencies.badhorsefix]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "CLIENT"


[[dependencies.badhorsefix]]
modId = "oculus"
mandatory = true
versionRange = "[1.2.0,1.7.0)"
ordering = "NONE"
side = "CLIENT"
