modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/doonguy/Bad-Horse-Fix/issues"
license = "LGPL-3.0-only"

[[mods]]
modId = "badhorsefix"
version = "${version}"
displayName = "Bad Horse Fix"
authors = "DoonGuy"
description = '''
Fixes horse markings appearing above horse armor when using Oculus
'''
logoFile = "assets/badhorsefix/icon.png"

[[dependencies.badhorsefix]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.badhorsefix]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"


[[dependencies.badhorsefix]]
modId = "oculus"
mandatory = true
versionRange = "[1.6.15a,)"
ordering = "NONE"
side = "BOTH"
